dd:
	wget http://res.pokemon.name/sprites/core/usum/front/019.01.png -o '19-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/020.01.png -o '20-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/026.01.png -o '26-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/027.01.png -o '27-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/028.01.png -o '28-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/037.01.png -o '37-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/038.01.png -o '38-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/050.01.png -o '50-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/051.01.png -o '51-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/052.01.png -o '52-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/053.01.png -o '53-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/074.01.png -o '74-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/075.01.png -o '75-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/076.01.png -o '76-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/088.01.png -o '88-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/089.01.png -o '89-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/103.01.png -o '103-alola.png'
	wget http://res.pokemon.name/sprites/core/usum/front/105.01.png -o '105-alola.png'

resize:
	convert 19-alola.png -resize 80x80 19-alola.png
